config/routes.rb
Tardisapi::Application.routes.draw do
  resources :users do
    resources :symptoms
    resources :events
  end


  get "home/index"









  root :to => 'home#index'

end

app/models/symptom.rb
class Symptom < ActiveRecord::Base
  validates :whichsymptom, :presence => true
  validates :whensymptom, :presence => true

  #attr_accessible :whichsymptom, :whensymptom

  belongs_to :user
end

app/controllers/symptoms_controller.rb
class SymptomsController < ApplicationController
  # GET /symptoms
  # GET /symptoms.json
  def index
    @user = User.find(params[:user_id])
    @symptoms = @user.symptoms
  end


  # GET /symptoms/1
  # GET /symptoms/1.json

  def show
    @user = User.find(params[:user_id])
    @symptom = @user.symptoms.find(params[:id])
  end



  # GET /symptoms/new
  # GET /symptoms/new.json
  def new
    @user = User.find(params[:user_id])
    @symptom = @user.symptoms.build
  end


  # GET /symptoms/1/edit
  def edit
    @user = User.find(params[:user_id])
    @symptom = @user.symptoms.find(params[:id])
  end

  # POST /symptoms
  # POST /symptoms.json
  def create
    @user = User.find(params[:user_id])
    @symptom = @user.symptoms.build(params[:symptom])
    if @symptom.save
      redirect_to user_symptom_url(@user, @symptom)
    else
      render :action => "new"
    end
  end


  # PUT /symptoms/1
  # PUT /symptoms/1.json
  def update
    @symptom = Symptom.find(params[:id])

    respond_to do |format|
      if @symptom.update_attributes(params[:symptom])
        format.html { redirect_to @symptom, notice: 'Symptom was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @symptom.errors, status: :unprocessable_entity }
      end
    end
  end



  # DELETE /symptoms/1
  # DELETE /symptoms/1.json
  def destroy
    @symptom = Symptom.find(params[:id])
    @symptom.destroy
  end
end

app/helpers/symptoms_helper.rb
module SymptomsHelper
end

app/views/symptoms/_form.html.erb
<%= form_for(@symptom.user, @symptom) do |f| %>
    <% if @symptom.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@symptom.errors.count, "error") %> prohibited this symptom from being saved:</h2>
          <ul>
            <% @symptom.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :'which symptom' %><br />
      <%= f.text_field :symptom %>
    </div>
    <div class="field">
      <%= f.label :'timing' %><br />
      <%= f.text_area :symptom %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/symptoms/edit.html.erb
<h1>Editing symptoms</h1>
<%= render 'form' %>
<br/>
<!-- /users/:user_id/symptoms/:id -->
<%= link_to 'Show', [@symptom.user, @symptom] %> |
<!-- /users/:user_id/symptoms/ -->
<%= link_to 'Back', user_symptoms_path(@symptom.user) %>

app/views/symptoms/index.html.erb
<h1>Listing symptoms</h1>
<h1>Symptoms for <%= @user.username %></h1>

<table>
  <tr>
    <th>Which Symptom</th>
    <th>When Symptom</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @symptoms.each do |symptom| %>
      <tr>
        <td><%= symptom %></td>
        <td><%= symptom %></td>
        <!-- /users/:user_id/symptoms/:id -->
        <td><%= link_to 'Show', [symptom.user, symptom] %></td>
        <!-- /users/:user_id/symptoms/:id/edit -->
        <td><%= link_to 'Edit', edit_user_symptom_path(symptom.user, symptom)%></td>
        <!-- /users/:user_id/symptoms/:id -->
        <td><%= link_to 'Destroy', [symptom.user, symptom], :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
  <% end %>

</table>

<%= link_to 'New symptom', new_user_symptom_path(@user) %>
<%= link_to 'Back to User', @user %>

app/views/symptoms/new.html.erb
<h1>New symptom will  go here when i figure this out</h1>

<%= form_for([@user, @symptom]) do |f| %>

    <p>Symptom <br />

    <p>
      <%= f.label :Symptom? %><br />
      <%= f.text_field :symptom %>
    </p>
    <p>
      <%= f.label :'Time' %><br />
      <%= f.text_area :symptom %>
    </p>

    <p>
      <%= f.submit "Create" %>
    </p>
<% end %>


<%= link_to 'Back', user_symptoms_path(@user) %>

app/views/symptoms/show.html.erb
<h1>This is the show symptoms page <%= @user.username %></h1>

<p id="notice"><%= notice %></p>
<p>
  <b>When did the symptom occur:</b>
  <%= @symptom %>
</p>
<p>
  <b>Body:</b>
  <%= @symptom %>
</p>
<!-- /users/:user_id/symptoms/:id/edit -->
<%= link_to 'Edit', edit_user_symptom_path(@symptom) %> |
<!-- /users/:user_id/symptoms/ -->
<%= link_to 'Back', user_symptom_path(@symptom.user) %>