config/routes.rb
Tardisapi::Application.routes.draw do
  resources :users do
    resources :symptoms
    resources :events
  end


  get "home/index"









  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :presence => true
  validates :password, :presence => true,
            :uniqueness => true,
            :length => { :is => 8 }
  validates :email, :presence => true,
            :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create }

  has_many :symptoms, :dependent => :destroy
  has_many :events,  :dependent => :destroy


  accepts_nested_attributes_for :symptoms, :allow_destroy => :true,
                                :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }

  accepts_nested_attributes_for :events, :allow_destroy => :true,
                                :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }


  attr_accessible :email, :password, :username, :events_attributes, :symptoms_attributes







end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def join_tags(users)
    user.events.map { |t| t.username}.join(", ")
  end
end

# you may need to change user.events back to user.tags

app/views/users/_form.html.erb
<% @user.events.build %>
<%= form_for(@user) do |post_form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= post_form.label :username %><br />
    <%= post_form.text_field :username %>
  </div>
  <div class="field">
    <%= post_form.label :password %><br />
    <%= post_form.text_field :password %>
  </div>
  <div class="field">
    <%= post_form.label :email %><br />
    <%= post_form.text_field :email %>
  </div>
  <div class="actions">
    <%= post_form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users: this page works! </h1>


<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.password %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Here i will put a list of symptoms and events:</b>
  <%= @user.events.map { |t| t.username }.join(", ") %>
</p>

<br/>
<h2>List of symptoms for <%= @user.username %></h2>
<p> i need to put in the rendered symptom form here. </p>

<br/>
<%= link_to 'Add Symptom', new_user_symptom_path(@user) %>
<br/>

<h2>List of events for <%= @user.username %></h2>
<p> i need to put in the rendered symptom form here. </p>
<br/>
<%= link_to 'Add Event', new_user_event_path(@user) %>

<br/>

<%= link_to 'Edit this Users profile', edit_user_path(@user) %> |
<%= link_to 'Back to All User', users_path %> |
