config/routes.rb
Tardisapi::Application.routes.draw do
  resources :users do
    resources :symptoms
    resources :events
  end


  get "home/index"









  root :to => 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :eventname, :presence => true
  validates :eventtime, :presence => true

  belongs_to :user

  #attr_accessible :eventname, :eventtime
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    # GET /users/:user_id/events
   # GET /users/:user_id/events.xml
    def index
      #1st you retrieve the user thanks to params[:user_id]
      user = User.find(params[:user_id])
      #2nd you get all the events of this user
      @events = user.events
      respond_to do |format|
        format.html # index.html.erb
        format.xml  { render :xml => @events }
      end
    end
    # GET /users/:user_id/events/:id
    # GET /events/:id.xml
    def show
      #1st you retrieve the user thanks to params[:user_id]
      user = User.find(params[:user_id])
      #2nd you retrieve the event thanks to params[:id]
      @event = user.events.find(params[:id])
      respond_to do |format|
        format.html # show.html.erb
        format.xml  { render :xml => @event }
      end
    end
    # GET /users/:user_id/events/new
    # GET /users/:user_id/events/new.xml
def new
  @user = User.find(params[:user_id])
  @event = @user.events.build
end
    # GET /users/:user_id/events/:id/edit
def edit
      #1st you retrieve the user thanks to params[:user_id]
  user = User.find(params[:user_id])
      #2nd you retrieve the event thanks to params[:id]
  @event = user.events.find(params[:id])
end
    # POST /users/:user_id/events
    # POST /users/:user_id/events.xml
def create
      #1st you retrieve the user thanks to params[:user_id]
  user = User.find(params[:user_id])
      #2nd you create the event with arguments in params[:event]
  @event = user.events.create(params[:event])
  respond_to do |format|
    if @event.save
          #1st argument of redirect_to is an array, in order to build the correct route to the nested resource event
      format.html { redirect_to([@event.user, @event], :notice => 'Comment was successfully created.') }
          #the key :location is associated to an array in order to build the correct route to the nested resource event
      format.xml  { render :xml => @event, :status => :created, :location => [@event.user, @event] }
    else
      format.html { render :action => "new" }
      format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
    end
  end
end


# PUT /users/:user_id/events/:id
# PUT /users/:user_id/events/:id.xml
def update
      #1st you retrieve the user thanks to params[:user_id]
  user = User.find(params[:user_id])
      #2nd you retrieve the event thanks to params[:id]
  @event = user.events.find(params[:id])
  respond_to do |format|
    if @event.update_attributes(params[:event])
          #1st argument of redirect_to is an array, in order to build the correct route to the nested resource event
      format.html { redirect_to([@event.user, @event], :notice => 'Comment was successfully updated.') }
      format.xml  { head :ok }
    else
      format.html { render :action => "edit" }
      format.xml  { render :xml => @event.errors, :status => :unprocessable_entity }
    end
  end
end
    # DELETE /users/:user_id/events/1
    # DELETE /users/:user_id/events/1.xml
    def destroy
      #1st you retrieve the user thanks to params[:user_id]
      user = User.find(params[:user_id])
      #2nd you retrieve the event thanks to params[:id]
      @event = user.events.find(params[:id])
      @event.destroy
      respond_to do |format|
        #1st argument reference the path /users/:user_id/events/
        format.html { redirect_to(user_events_url) }
        format.xml  { head :ok }
      end
    end
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.erb
<%= form_for([@event.user, @event]) do |f| %>
    <% if @event.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
          <ul>
            <% @event.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :eventname %><br />
      <%= f.text_field :eventname %>
    </div>
    <div class="field">
      <%= f.label :eventtime %><br />
      <%= f.text_area :eventtime %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>
<%= render 'form' %>
<!-- /users/:user_id/events/:id -->
<%= link_to 'Show', [@event.user, @event] %> |
<!-- /users/:user_id/events/ -->
<%= link_to 'Back', user_event_path(@event.user) %>

app/views/events/index.erb
<h1>Listing all events</h1>
<table>
  <tr>
    <th>Eventname</th>
    <th>Eventtime</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @events.each do |event| %>
      <tr>
        <td><%= @events.eventname %></td>
        <td><%= @events.eventtime %></td>
        <!-- /users/:user_id/events/:id -->
        <td><%= link_to 'Show', [event.user, event] %></td>
        <!-- /users/:user_id/events/:id/edit -->
        <td><%= link_to 'Edit', edit_user_event_path(event.user, event)%></td>
        <!-- /users/:user_id/events/:id -->
        <td><%= link_to 'Destroy', [event.user, event], :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
  <% end %>
</table>
<br />
<%= link_to 'New Event', new_user_event_path %> <!-- /users/:user_id/events/new -->

app/views/events/new.html.erb
<h1>New event</h1>


<%= render 'form' %>
<!-- /users/:user_id/events/ -->
<%= link_to 'Back', user_event_path(@event.user)%>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Eventname:</b>
  <%= @event.eventname %>
</p>
<p>
  <b>Event time:</b>
  <%= @event.eventtime %>
</p>
<!-- /users/:user_id/events/:id/edit -->
<%= link_to 'Edit', edit_user_event_path(@event.user, @event) %> |
<!-- /users/:user_id/events/ -->
<%= link_to 'Back', user_events_path(@event.user) %>